name: stadata_flutter_sdk
description: |
  Streamline BPS Statistics API integration in Flutter. Easily fetch, analyze, and visualize data.
homepage: https://pub.dev/packages/stadata_flutter_sdk
repository: https://github.com/ryanaidilp/stadata_flutter_sdk
version: 0.5.0+11
# publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.2
  dio_cache_interceptor: ^3.4.2
  dio_smart_retry: ^5.0.0
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  logger: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://saweria.co/ryanaidilp
